Class {
	#name : #FamixTest6UnknownSourceLanguage,
	#superclass : #FamixTest6SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Test6-Entities-Entities'
}

{ #category : #meta }
FamixTest6UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixTest6SourceLanguage>
	<package: #'Famix-Test6-Entities'>
	<generated>
	^self
]
