Class {
	#name : #FamixTest6SourceTextAnchor,
	#superclass : #FamixTest6SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Test6-Entities-Entities'
}

{ #category : #meta }
FamixTest6SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixTest6SourceAnchor>
	<package: #'Famix-Test6-Entities'>
	<generated>
	^ self
]
