Class {
	#name : #FamixTest6NamedEntity,
	#superclass : #FamixTest6SourcedEntity,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Famix-Test6-Entities-Entities'
}

{ #category : #meta }
FamixTest6NamedEntity class >> annotation [

	<FMClass: #NamedEntity super: #FamixTest6SourcedEntity>
	<package: #'Famix-Test6-Entities'>
	<generated>
	^self
]
