Trait {
	#name : #FamixTWithPackages,
	#category : #'Famix-Deprecated-Package'
}

{ #category : #meta }
FamixTWithPackages classSide >> annotation [

	<FMClass: #TWithPackages super: #Object>
	<package: #'Famix-Traits'>
	<generated>
	^self
]

{ #category : #accessing }
FamixTWithPackages >> addPackage: anObject [
	

]

{ #category : #accessing }
FamixTWithPackages >> packages [
	"Relation named: #packages type: #FamixTPackage opposite: #packageOwner"

	
]

{ #category : #accessing }
FamixTWithPackages >> packages: anObject [

	
]
