Class {
	#name : 'FamixTestComposed1CustomEntity3',
	#superclass : 'FamixTestComposed1Entity',
	#category : 'Famix-TestComposedSubmetamodel1-Entities-Entities',
	#package : 'Famix-TestComposedSubmetamodel1-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTestComposed1CustomEntity3 class >> annotation [

	<ignoreForCoverage>
	<FMClass: #CustomEntity3 super: #FamixTestComposed1Entity>
	<package: #'Famix-TestComposedSubmetamodel1-Entities'>
	<generated>
]
