Class {
	#name : 'FamixTestComposed1CustomEntity2',
	#superclass : 'FamixTestComposed1Entity',
	#category : 'Famix-TestComposedSubmetamodel1-Entities-Entities',
	#package : 'Famix-TestComposedSubmetamodel1-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTestComposed1CustomEntity2 class >> annotation [

	<FMClass: #CustomEntity2 super: #FamixTestComposed1Entity>
	<package: #'Famix-TestComposedSubmetamodel1-Entities'>
	<generated>
	^ self
]
