Class {
	#name : #FAMIXModel,
	#superclass : #MooseModel,
	#category : #'Famix-Compatibility-Entities-Model'
}

{ #category : #accessing }
FAMIXModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FAMIXModel class >> annotation [
	<FMClass: #FAMIXModel super: #MooseModel>
	<package: #FAMIX>
	<generated>
]

{ #category : #testing }
FAMIXModel >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isBehavioural [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isClass [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isFunction [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isImplicitVariable [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isInheritance [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isNamespace [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isPackage [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isPrimitiveType [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isStructuralEntity [

	<generated>
	^ false
]

{ #category : #testing }
FAMIXModel >> isType [

	<generated>
	^ false
]
