Class {
	#name : #CppUnknownSourceLanguage,
	#superclass : #CppSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Cpp-Entities-Entities'
}

{ #category : #meta }
CppUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #CppSourceLanguage>
	<package: #'Cpp-Entities'>
	<generated>
	^self
]
