Trait {
	#name : 'FamixTest1TEntity',
	#traits : 'TEntityMetaLevelDependency',
	#classTraits : 'TEntityMetaLevelDependency classTrait',
	#category : 'Famix-Test1-Entities-Traits',
	#package : 'Famix-Test1-Entities',
	#tag : 'Traits'
}

{ #category : 'meta' }
FamixTest1TEntity classSide >> annotation [

	<ignoreForCoverage>
	<FMClass: #TEntity super: #Object>
	<package: #'Famix-Test1-Entities'>
	<generated>
]
