Class {
	#name : 'FamixTest1Entity',
	#superclass : 'MooseEntity',
	#category : 'Famix-Test1-Entities-Entities',
	#package : 'Famix-Test1-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTest1Entity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-Test1-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FamixTest1Entity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixTest1Entity
]

{ #category : 'meta' }
FamixTest1Entity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixTest1Model metamodel
]

{ #category : 'testing' }
FamixTest1Entity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isFileAnchor [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest1Entity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
