Class {
	#name : #FamixTest7SourceTextAnchor,
	#superclass : #FamixTest7SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Test7-Entities-Entities'
}

{ #category : #meta }
FamixTest7SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixTest7SourceAnchor>
	<package: #'Famix-Test7-Entities'>
	<generated>
	^ self
]
