Class {
	#name : 'FamixTest7Entity',
	#superclass : 'MooseEntity',
	#category : 'Famix-Test7-Entities-Entities',
	#package : 'Famix-Test7-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTest7Entity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-Test7-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FamixTest7Entity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixTest7Entity
]

{ #category : 'meta' }
FamixTest7Entity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixTest7Model metamodel
]

{ #category : 'testing' }
FamixTest7Entity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isInheritance [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest7Entity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
