Class {
	#name : #FamixAnnotationInstanceGroup,
	#superclass : #MooseSpecializedGroup,
	#category : #'Famix-Traits-Groups'
}

{ #category : #meta }
FamixAnnotationInstanceGroup class >> annotation [

	<FMClass: #AnnotationInstanceGroup super: #MooseSpecializedGroup>
	<package: #'Famix-Traits'>
	<generated>
	^ self
]

{ #category : #meta }
FamixAnnotationInstanceGroup class >> metamodel [

	<generated>
	^ FamixModel metamodel
]
