Trait {
	#name : 'FamixTest5TEntity',
	#traits : 'TEntityMetaLevelDependency',
	#classTraits : 'TEntityMetaLevelDependency classTrait',
	#category : 'Famix-Test5-Entities-Traits',
	#package : 'Famix-Test5-Entities',
	#tag : 'Traits'
}

{ #category : 'meta' }
FamixTest5TEntity classSide >> annotation [

	<ignoreForCoverage>
	<FMClass: #TEntity super: #Object>
	<package: #'Famix-Test5-Entities'>
	<generated>
]
