Extension { #name : #UndefinedObject }

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allWithScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atAnyScope: aCollectionOfFamixScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> withScopeIn: aCollection [
	^ aCollection
]
