Extension { #name : #UndefinedObject }

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allWithScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atAnyScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toAnyScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toScopeIn: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> withScopeIn: aCollection [
	^ aCollection
]
