Class {
	#name : 'MooseMSEImporterTestModel',
	#superclass : 'MooseModel',
	#traits : 'MooseMSEImporterTestTEntityCreator',
	#classTraits : 'MooseMSEImporterTestTEntityCreator classTrait',
	#category : 'Moose-Core-Tests-Entities-Model',
	#package : 'Moose-Core-Tests-Entities',
	#tag : 'Model'
}

{ #category : 'accessing' }
MooseMSEImporterTestModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : 'meta' }
MooseMSEImporterTestModel class >> annotation [
	<FMClass: #MooseMSEImporterTestModel super: #MooseModel>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
]
