Class {
	#name : #MooseMSEImporterTestSourceLanguage,
	#superclass : #MooseMSEImporterTestEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Moose-Core-Tests-Entities-Entities'
}

{ #category : #meta }
MooseMSEImporterTestSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #MooseMSEImporterTestEntity>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
	^ self
]
