Class {
	#name : #MooseMSEImporterTestMethod,
	#superclass : #MooseMSEImporterTestNamedEntity,
	#traits : 'FamixTMethod',
	#classTraits : 'FamixTMethod classTrait',
	#category : #'Moose-Core-Tests-Entities-Entities'
}

{ #category : #meta }
MooseMSEImporterTestMethod class >> annotation [

	<FMClass: #Method super: #MooseMSEImporterTestNamedEntity>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
	^self
]
