Class {
	#name : #MooseMSEImporterTestPrimitiveType,
	#superclass : #MooseMSEImporterTestEntity,
	#traits : 'FamixTPrimitiveType',
	#classTraits : 'FamixTPrimitiveType classTrait',
	#category : #'Moose-Core-Tests-Entities-Entities'
}

{ #category : #meta }
MooseMSEImporterTestPrimitiveType class >> annotation [

	<FMClass: #PrimitiveType super: #MooseMSEImporterTestEntity>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
	^self
]
