Class {
	#name : 'MooseMSEImporterTestEntity',
	#superclass : 'MooseEntity',
	#category : 'Moose-Core-Tests-Entities-Entities',
	#package : 'Moose-Core-Tests-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
MooseMSEImporterTestEntity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
MooseMSEImporterTestEntity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == MooseMSEImporterTestEntity
]

{ #category : 'meta' }
MooseMSEImporterTestEntity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ MooseMSEImporterTestModel metamodel
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isInheritance [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isNamespace [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isPackage [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isPrimitiveType [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
MooseMSEImporterTestEntity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
