Class {
	#name : #MooseMSEImporterTestSourceTextAnchor,
	#superclass : #MooseMSEImporterTestSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Moose-Core-Tests-Entities-Entities'
}

{ #category : #meta }
MooseMSEImporterTestSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #MooseMSEImporterTestSourceAnchor>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
	^self
]
