Class {
	#name : #MooseMSEImporterTestInheritance,
	#superclass : #MooseMSEImporterTestEntity,
	#traits : 'FamixTInheritance',
	#classTraits : 'FamixTInheritance classTrait',
	#category : #'Moose-Core-Tests-Entities-Entities'
}

{ #category : #meta }
MooseMSEImporterTestInheritance class >> annotation [

	<FMClass: #Inheritance super: #MooseMSEImporterTestEntity>
	<package: #'Moose-Core-Tests-Entities'>
	<generated>
	^ self
]
