Class {
	#name : 'FmxTraitsTestGenerateAccessorAModel',
	#superclass : 'MooseModel',
	#category : 'Famix-MetamodelBuilder-TestsTraitsResources-A-Model',
	#package : 'Famix-MetamodelBuilder-TestsTraitsResources-A',
	#tag : 'Model'
}

{ #category : 'meta' }
FmxTraitsTestGenerateAccessorAModel class >> annotation [
	<FMClass: #FmxTraitsTestGenerateAccessorAModel super: #MooseModel>
	<package: #'Famix-MetamodelBuilder-TestsTraitsResources-A'>
	<generated>
]
