Class {
	#name : #FamixJavaModel,
	#superclass : #MooseModel,
	#category : #'Famix-Java-Entities-Model'
}

{ #category : #accessing }
FamixJavaModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixJavaModel class >> annotation [
	<FMClass: #FamixJavaModel super: #MooseModel>
	<package: #'Famix-Java-Entities'>
	<generated>
]

{ #category : #testing }
FamixJavaModel >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isBehavioural [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isClass [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isImplicitVariable [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isInheritance [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isNamespace [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isPackage [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isPrimitiveType [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isStructuralEntity [

	<generated>
	^ false
]

{ #category : #testing }
FamixJavaModel >> isType [

	<generated>
	^ false
]
