Class {
	#name : #FamixJavaParameterConcretisation,
	#superclass : #FamixJavaEntity,
	#traits : 'FamixTParameterConcretisation',
	#classTraits : 'FamixTParameterConcretisation classTrait',
	#category : #'Famix-Java-Entities-Entities'
}

{ #category : #meta }
FamixJavaParameterConcretisation class >> annotation [

	<FMClass: #ParameterConcretisation super: #FamixJavaEntity>
	<package: #'Famix-Java-Entities'>
	<generated>
	^ self
]
