Class {
	#name : 'FamixJavaEntity',
	#superclass : 'MooseEntity',
	#category : 'Famix-Java-Entities-Entities',
	#package : 'Famix-Java-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixJavaEntity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-Java-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FamixJavaEntity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixJavaEntity
]

{ #category : 'meta' }
FamixJavaEntity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixJavaModel metamodel
]

{ #category : 'testing' }
FamixJavaEntity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isAccess [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isEnumValue [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isException [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isFileAnchor [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isImplicitVariable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isInheritance [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isInterface [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isInvocation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isLocalVariable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isPackage [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isParametricAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isParametricEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isPrimitiveType [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isReference [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixJavaEntity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
