Class {
	#name : 'FamixStEntity',
	#superclass : 'MooseEntity',
	#category : 'Famix-PharoSmalltalk-Entities-Entities',
	#package : 'Famix-PharoSmalltalk-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixStEntity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-PharoSmalltalk-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FamixStEntity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixStEntity
]

{ #category : 'meta' }
FamixStEntity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixStModel metamodel
]

{ #category : 'testing' }
FamixStEntity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isAccess [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isGlobalVariable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isImplicitVariable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isInheritance [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isInvocation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isLocalVariable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isNamespace [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isPackage [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isParametricEntity [

	^ false
]

{ #category : 'testing' }
FamixStEntity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isReference [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isSharedVariable [
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixStEntity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
