"
This trait is used by Famix models.
It provides an API for creating entities and adding them to the model.


"
Trait {
	#name : 'FamixTestComposed3TEntityCreator',
	#category : 'Famix-TestComposed3Metamodel-Entities-Model',
	#package : 'Famix-TestComposed3Metamodel-Entities',
	#tag : 'Model'
}

{ #category : 'meta' }
FamixTestComposed3TEntityCreator classSide >> annotation [

	<FMClass: #TEntityCreator super: #Object>
	<package: #'Famix-TestComposed3Metamodel-Entities'>
	<generated>
]
