Class {
	#name : #FamixTest2Entity,
	#superclass : #MooseEntity,
	#category : #'Famix-Test2-Entities-Entities'
}

{ #category : #meta }
FamixTest2Entity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-Test2-Entities'>
	<generated>
	<abstract>
]

{ #category : #testing }
FamixTest2Entity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixTest2Entity
]

{ #category : #meta }
FamixTest2Entity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixTest2Model metamodel
]

{ #category : #testing }
FamixTest2Entity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isAccess [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isInvocation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isPackage [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isParametricEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isReference [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : #testing }
FamixTest2Entity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
