Class {
	#name : 'FDModel',
	#superclass : 'MooseModel',
	#traits : 'FDTEntityCreator',
	#classTraits : 'FDTEntityCreator classTrait',
	#category : 'FamixDocumentor-TestMetaModel-Model',
	#package : 'FamixDocumentor-TestMetaModel',
	#tag : 'Model'
}

{ #category : 'meta' }
FDModel class >> annotation [

	<FMClass: #Model super: #MooseModel>
	<package: #'FamixDocumentor-TestMetaModel'>
	<generated>
]
