"
This trait is used by Famix models.
It provides an API for creating entities and adding them to the model.


"
Trait {
	#name : 'FamixTestComposedComposedTEntityCreator',
	#category : 'Famix-TestComposedComposedMetamodel-Entities-Model',
	#package : 'Famix-TestComposedComposedMetamodel-Entities',
	#tag : 'Model'
}

{ #category : 'meta' }
FamixTestComposedComposedTEntityCreator classSide >> annotation [

	<FMClass: #TEntityCreator super: #Object>
	<package: #'Famix-TestComposedComposedMetamodel-Entities'>
	<generated>
	^ self
]
