Trait {
	#name : #FmxMBTestOnlyTraits1GeneratorTC,
	#traits : 'FmxMBTestOnlyTraits1GeneratorTA',
	#classTraits : 'FmxMBTestOnlyTraits1GeneratorTA classTrait',
	#category : #'Famix-MetamodelBuilder-TestOnlyTraits'
}

{ #category : #meta }
FmxMBTestOnlyTraits1GeneratorTC classSide >> annotation [

	<FMClass: #TC super: #Object>
	<package: #'Famix-MetamodelBuilder-TestOnlyTraits'>
	<generated>
	^self
]
