Class {
	#name : 'FamixTestComposed2CustomEntity3',
	#superclass : 'FamixTestComposed2Entity',
	#category : 'Famix-TestComposedSubmetamodel2-Entities-Entities',
	#package : 'Famix-TestComposedSubmetamodel2-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTestComposed2CustomEntity3 class >> annotation [

	<ignoreForCoverage>
	<FMClass: #CustomEntity3 super: #FamixTestComposed2Entity>
	<package: #'Famix-TestComposedSubmetamodel2-Entities'>
	<generated>
]
