Class {
	#name : 'FamixTest3Entity',
	#superclass : 'MooseEntity',
	#category : 'Famix-Test3-Entities-Entities',
	#package : 'Famix-Test3-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixTest3Entity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'Famix-Test3-Entities'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FamixTest3Entity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FamixTest3Entity
]

{ #category : 'meta' }
FamixTest3Entity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FamixTest3Model metamodel
]

{ #category : 'testing' }
FamixTest3Entity >> canBeStub [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isAccess [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isAssociation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isAttribute [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isBehavioural [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isClass [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isComment [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isInvocation [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isMethod [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isNamedEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isPackage [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isParametricEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isQueryable [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isReference [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isStructuralEntity [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'testing' }
FamixTest3Entity >> isType [

	<ignoreForCoverage>
	<generated>
	^ false
]
