Class {
	#name : #FmxTraitsTestGenerateAccessorBModel,
	#superclass : #MooseModel,
	#category : #'Famix-MetamodelBuilder-TestsTraitsResources-B-Model'
}

{ #category : #accessing }
FmxTraitsTestGenerateAccessorBModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #('Famix-MetamodelBuilder-TestsTraitsResources-A')
]

{ #category : #meta }
FmxTraitsTestGenerateAccessorBModel class >> annotation [
	<FMClass: #FmxTraitsTestGenerateAccessorBModel super: #MooseModel>
	<package: #'Famix-MetamodelBuilder-TestsTraitsResources-B'>
	<generated>
]
