Class {
	#name : #FmxTraitsTestGenerateAccessorBClassB,
	#superclass : #FmxTraitsTestGenerateAccessorBEntity,
	#traits : 'FmxTraitsTestGenerateAccessorBTraitB',
	#classTraits : 'FmxTraitsTestGenerateAccessorBTraitB classTrait',
	#category : #'Famix-MetamodelBuilder-TestsTraitsResources-B-Entities'
}

{ #category : #meta }
FmxTraitsTestGenerateAccessorBClassB class >> annotation [

	<FMClass: #ClassB super: #FmxTraitsTestGenerateAccessorBEntity>
	<package: #'Famix-MetamodelBuilder-TestsTraitsResources-B'>
	<generated>
	^self
]
